// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Quan_Ly_Nha_Tro.Models;

#nullable disable

namespace Quan_Ly_Nha_Tro.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260924004132_AddIdentityTables")]
    partial class AddIdentityTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Quan_Ly_Nha_Tro.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Quan_Ly_Nha_Tro.Models.BaoTri", b =>
                {
                    b.Property<int>("BaoTriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BaoTriId"));

                    b.Property<decimal>("ChiPhiDuKien")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("ChiPhiThucTe")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("MoTaVanDe")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly?>("NgayHoanThanh")
                        .HasColumnType("date");

                    b.Property<DateOnly>("NgayYeuCau")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NguoiChiuChiPhi")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("CHU_TRO");

                    b.Property<int>("PhongId")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("CHO_XU_LY");

                    b.HasKey("BaoTriId")
                        .HasName("PK__BaoTri__56159A50CB47686B");

                    b.HasIndex("PhongId");

                    b.ToTable("BaoTri", (string)null);
                });

            modelBuilder.Entity("Quan_Ly_Nha_Tro.Models.ChiSoDienNuoc", b =>
                {
                    b.Property<long>("ChiSoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ChiSoId"));

                    b.Property<decimal>("DienCu")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("DienMoi")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("Nam")
                        .HasColumnType("int");

                    b.Property<DateOnly>("NgayGhi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal>("NuocCu")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("NuocMoi")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("PhongId")
                        .HasColumnType("int");

                    b.Property<int>("Thang")
                        .HasColumnType("int");

                    b.Property<decimal?>("TieuThuDien")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(19, 2)")
                        .HasComputedColumnSql("([DienMoi]-[DienCu])", false);

                    b.Property<decimal?>("TieuThuNuoc")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(19, 2)")
                        .HasComputedColumnSql("([NuocMoi]-[NuocCu])", false);

                    b.HasKey("ChiSoId")
                        .HasName("PK__ChiSoDie__3746C156E9749FA4");

                    b.HasIndex(new[] { "PhongId", "Thang", "Nam" }, "UQ_ChiSo_Phong_ThangNam")
                        .IsUnique();

                    b.ToTable("ChiSoDienNuoc", (string)null);
                });

            modelBuilder.Entity("Quan_Ly_Nha_Tro.Models.ChiTietHoaDon", b =>
                {
                    b.Property<long>("ChiTietHoaDonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ChiTietHoaDonId"));

                    b.Property<int?>("DichVuId")
                        .HasColumnType("int");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<long>("HoaDonId")
                        .HasColumnType("bigint");

                    b.Property<string>("LoaiKhoanThu")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("NoiDung")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("SoLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(1m);

                    b.Property<decimal?>("ThanhTien")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(18, 2)")
                        .HasComputedColumnSql("(CONVERT([decimal](18,2),[SoLuong]*[DonGia]))", false);

                    b.HasKey("ChiTietHoaDonId")
                        .HasName("PK__ChiTietH__6BB67135ED5F235E");

                    b.HasIndex("DichVuId");

                    b.HasIndex("HoaDonId");

                    b.ToTable("ChiTietHoaDon", (string)null);
                });

            modelBuilder.Entity("Quan_Ly_Nha_Tro.Models.DichVu", b =>
                {
                    b.Property<int>("DichVuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DichVuId"));

                    b.Property<decimal>("DonGiaHienTai")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TenDichVu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("DichVuId")
                        .HasName("PK__DichVu__8DB8EDC18E7ACDA2");

                    b.HasIndex(new[] { "TenDichVu" }, "UQ_DichVu_Ten")
                        .IsUnique();

                    b.ToTable("DichVu", (string)null);
                });

            modelBuilder.Entity("Quan_Ly_Nha_Tro.Models.HoaDon", b =>
                {
                    b.Property<long>("HoaDonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("HoaDonId"));

                    b.Property<DateOnly?>("HanThanhToan")
                        .HasColumnType("date");

                    b.Property<int>("HopDongId")
                        .HasColumnType("int");

                    b.Property<int>("Nam")
                        .HasColumnType("int");

                    b.Property<DateOnly>("NgayLap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("Thang")
                        .HasColumnType("int");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)")
                        .HasDefaultValue("CHUA_THANH_TOAN");

                    b.HasKey("HoaDonId")
                        .HasName("PK__HoaDon__6956CE499B86CA30");

                    b.HasIndex(new[] { "HopDongId", "Thang", "Nam" }, "UQ_HoaDon_HopDong_ThangNam")
                        .IsUnique();

                    b.ToTable("HoaDon", (string)null);
                });

            modelBuilder.Entity("Quan_Ly_Nha_Tro.Models.HopDong", b =>
                {
                    b.Property<int>("HopDongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HopDongId"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("GiaThue")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateOnly>("NgayBatDau")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("NgayKetThuc")
                        .HasColumnType("date");

                    b.Property<int>("PhongId")
                        .HasColumnType("int");

                    b.Property<decimal>("TienCoc")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("HIEU_LUC");

                    b.HasKey("HopDongId")
                        .HasName("PK__HopDong__A2D6D347AE0FED25");

                    b.HasIndex("PhongId");

                    b.ToTable("HopDong", (string)null);
                });

            modelBuilder.Entity("Quan_Ly_Nha_Tro.Models.HopDongKhachThue", b =>
                {
                    b.Property<int>("HopDongId")
                        .HasColumnType("int");

                    b.Property<int>("KhachThueId")
                        .HasColumnType("int");

                    b.Property<bool>("LaNguoiDaiDien")
                        .HasColumnType("bit");

                    b.Property<DateOnly?>("NgayRoiDi")
                        .HasColumnType("date");

                    b.Property<DateOnly>("NgayThamGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("HopDongId", "KhachThueId");

                    b.HasIndex("KhachThueId");

                    b.HasIndex(new[] { "HopDongId" }, "UX_HopDong_NguoiDaiDien")
                        .IsUnique()
                        .HasFilter("([LaNguoiDaiDien]=(1))");

                    b.ToTable("HopDong_KhachThue", (string)null);
                });

            modelBuilder.Entity("Quan_Ly_Nha_Tro.Models.KhachThue", b =>
                {
                    b.Property<int>("KhachThueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KhachThueId"));

                    b.Property<string>("Cccd")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("CCCD");

                    b.Property<string>("DiaChiThuongTru")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("KhachThueId")
                        .HasName("PK__KhachThu__9FD07F1C8DD93AFF");

                    b.HasIndex(new[] { "Cccd" }, "UQ_KhachThue_CCCD")
                        .IsUnique();

                    b.ToTable("KhachThue", (string)null);
                });

            modelBuilder.Entity("Quan_Ly_Nha_Tro.Models.PhongTro", b =>
                {
                    b.Property<int>("PhongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhongId"));

                    b.Property<decimal>("DienTich")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<decimal>("GiaThue")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SoPhong")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("Tang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("TRONG");

                    b.HasKey("PhongId")
                        .HasName("PK__PhongTro__FC6699A7D9656898");

                    b.HasIndex(new[] { "SoPhong" }, "UQ_PhongTro_SoPhong")
                        .IsUnique();

                    b.ToTable("PhongTro", (string)null);
                });

            modelBuilder.Entity("Quan_Ly_Nha_Tro.Models.ThanhToan", b =>
                {
                    b.Property<long>("ThanhToanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ThanhToanId"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("HoaDonId")
                        .HasColumnType("bigint");

                    b.Property<string>("MaGiaoDich")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("NgayThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("PhuongThuc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("ThanhToanId")
                        .HasName("PK__ThanhToa__24A8D6E48E01FAD2");

                    b.HasIndex("HoaDonId");

                    b.ToTable("ThanhToan", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Quan_Ly_Nha_Tro.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Quan_Ly_Nha_Tro.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Quan_Ly_Nha_Tro.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Quan_Ly_Nha_Tro.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Quan_Ly_Nha_Tro.Models.BaoTri", b =>
                {
                    b.HasOne("Quan_Ly_Nha_Tro.Models.PhongTro", "Phong")
                        .WithMany("BaoTris")
                        .HasForeignKey("PhongId")
                        .IsRequired()
                        .HasConstraintName("FK_BaoTri_Phong");

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("Quan_Ly_Nha_Tro.Models.ChiSoDienNuoc", b =>
                {
                    b.HasOne("Quan_Ly_Nha_Tro.Models.PhongTro", "Phong")
                        .WithMany("ChiSoDienNuocs")
                        .HasForeignKey("PhongId")
                        .IsRequired()
                        .HasConstraintName("FK_ChiSo_Phong");

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("Quan_Ly_Nha_Tro.Models.ChiTietHoaDon", b =>
                {
                    b.HasOne("Quan_Ly_Nha_Tro.Models.DichVu", "DichVu")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("DichVuId")
                        .HasConstraintName("FK_ChiTietHoaDon_DichVu");

                    b.HasOne("Quan_Ly_Nha_Tro.Models.HoaDon", "HoaDon")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("HoaDonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ChiTietHoaDon_HoaDon");

                    b.Navigation("DichVu");

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("Quan_Ly_Nha_Tro.Models.HoaDon", b =>
                {
                    b.HasOne("Quan_Ly_Nha_Tro.Models.HopDong", "HopDong")
                        .WithMany("HoaDons")
                        .HasForeignKey("HopDongId")
                        .IsRequired()
                        .HasConstraintName("FK_HoaDon_HopDong");

                    b.Navigation("HopDong");
                });

            modelBuilder.Entity("Quan_Ly_Nha_Tro.Models.HopDong", b =>
                {
                    b.HasOne("Quan_Ly_Nha_Tro.Models.PhongTro", "Phong")
                        .WithMany("HopDongs")
                        .HasForeignKey("PhongId")
                        .IsRequired()
                        .HasConstraintName("FK_HopDong_Phong");

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("Quan_Ly_Nha_Tro.Models.HopDongKhachThue", b =>
                {
                    b.HasOne("Quan_Ly_Nha_Tro.Models.HopDong", "HopDong")
                        .WithOne("HopDongKhachThue")
                        .HasForeignKey("Quan_Ly_Nha_Tro.Models.HopDongKhachThue", "HopDongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_HDKT_HopDong");

                    b.HasOne("Quan_Ly_Nha_Tro.Models.KhachThue", "KhachThue")
                        .WithMany("HopDongKhachThues")
                        .HasForeignKey("KhachThueId")
                        .IsRequired()
                        .HasConstraintName("FK_HDKT_KhachThue");

                    b.Navigation("HopDong");

                    b.Navigation("KhachThue");
                });

            modelBuilder.Entity("Quan_Ly_Nha_Tro.Models.ThanhToan", b =>
                {
                    b.HasOne("Quan_Ly_Nha_Tro.Models.HoaDon", "HoaDon")
                        .WithMany("ThanhToans")
                        .HasForeignKey("HoaDonId")
                        .IsRequired()
                        .HasConstraintName("FK_ThanhToan_HoaDon");

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("Quan_Ly_Nha_Tro.Models.DichVu", b =>
                {
                    b.Navigation("ChiTietHoaDons");
                });

            modelBuilder.Entity("Quan_Ly_Nha_Tro.Models.HoaDon", b =>
                {
                    b.Navigation("ChiTietHoaDons");

                    b.Navigation("ThanhToans");
                });

            modelBuilder.Entity("Quan_Ly_Nha_Tro.Models.HopDong", b =>
                {
                    b.Navigation("HoaDons");

                    b.Navigation("HopDongKhachThue");
                });

            modelBuilder.Entity("Quan_Ly_Nha_Tro.Models.KhachThue", b =>
                {
                    b.Navigation("HopDongKhachThues");
                });

            modelBuilder.Entity("Quan_Ly_Nha_Tro.Models.PhongTro", b =>
                {
                    b.Navigation("BaoTris");

                    b.Navigation("ChiSoDienNuocs");

                    b.Navigation("HopDongs");
                });
#pragma warning restore 612, 618
        }
    }
}
